# api call for category list

###
GET  http://127.0.0.1:8000/api/category/

# api call for adding category
###
POST http://127.0.0.1:8000/api/category/
Content-Type: application/json

{
    "name":"fruits"
}


# ======product manage=====

#api call for adding a new product

###

POST http://127.0.0.1:8000/api/category/1/products/
Content-Type: application/json

{
    "title":"potatto",
    "description":"potatto description",
    "price":65

}

# api call listing all products

###

POST http://127.0.0.1:8000/api/products/
Content-Type: application/json

{
    "title":"carrot",
    "description":"carrot description",
    "price":75

}

# specific product detail
###
GET http://127.0.0.1:8000/api/products/
# ? optional query parameter


# Api call for creating order
###
POST http://127.0.0.1:8000/api/orders/
Content-Type: application/json

{
    "phone":"9526562826"
}

# Api call for adding order item to a order
###

POST  http://127.0.0.1:8000/api/orders/1/items/
Content-Type: application/json

{
    "product_object":1,
    "qty":1

}


# api for order detail view
###
GET  http://127.0.0.1:8000/api/orders/1/



# Api for generating bill

###

PUT http://127.0.0.1:8000/api/orders/1/generate-bill/
